---
apiVersion: v1
kind: Service
metadata:
  name: nginx 
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    nodePort: 32084
    targetPort: 80
    name: nginx
  selector:
    app: nginx
